language: node_js
services:
- docker
node_js:
- '7'
env:
  global:
  - CXX=g++-4.9
  - CC=gcc-4.9
  - DISPLAY=:99.0
before_install:
- sh -e /etc/init.d/xvfb start
install:
- npm install --no-save
- npm install -g vsce
script:
- npm run gulp
- npm run integration-test
- vsce package